# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 10:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2, verbose_name='FIPS code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('area', models.IntegerField(verbose_name='area')),
                ('pop2005', models.BigIntegerField(verbose_name='population in 2005')),
                ('region', models.IntegerField(verbose_name='region code')),
                ('subregion', models.IntegerField(verbose_name='sub-region code')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
    ]
