# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 11:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('type', models.CharField(choices=[('festival', 'Festival'), ('openair', 'Open air'), ('indoor', 'Indoor'), ('club', 'Club'), ('indoor_outdoor', 'In- and outdoor')], default='indoor', max_length=14, verbose_name='type')),
                ('town', models.CharField(max_length=100, verbose_name='town')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('lineup', models.TextField(verbose_name='lineup')),
                ('decoration', models.TextField(verbose_name='decoration')),
                ('entry_fee', models.TextField(verbose_name='entry fee')),
                ('more', models.TextField(verbose_name='more')),
                ('organizer_name', models.CharField(max_length=255, verbose_name='organizer name')),
                ('organizer_text', models.TextField(verbose_name='organizer text')),
                ('organizer_url', models.TextField(verbose_name='organizer URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('moved', 'Moved')], default='scheduled', max_length=9, verbose_name='status')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'verbose_name': 'party',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
    ]
