# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 15:45
from __future__ import unicode_literals

from django.contrib.gis.utils import LayerMapping
from django.db import migrations

from goabase.modules.countries.models import country_mapping


def import_countries(apps, schema_editor):
    Country = apps.get_model('countries', 'Country')
    lm = LayerMapping(Country, 'TM_WORLD_BORDERS-0.3.shp', country_mapping,
                      encoding='iso-8859-1', unique='iso2')
    lm.save(strict=True, verbose=True)


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_countries),
    ]
